### ISSUE TITLE
logextract and logviewer bug

### ISSUE THREAD

**Issue by swhaKo** [roborescue/rcrs-server#10]
Hi, The last issue is completely resolved! Thank you again.

There seems to be a bug in logextract.sh and logviewer.sh.
When I type the command **./logextract.sh logs/traffic-out.log ./** ,
Exception in thread "main" java.lang.IllegalArgumentException: Unrecognised RecordType: 1414676803
	at rescuecore2.log.RecordType.fromID(RecordType.java:48)
	at rescuecore2.log.FileLogReader.index(FileLogReader.java:181)
	at rescuecore2.log.FileLogReader.<init>(FileLogReader.java:64)
	at rescuecore2.log.FileLogReader.<init>(FileLogReader.java:50)
	at rescuecore2.log.LogExtractor.main(LogExtractor.java:179)
An error such as is shown on the last output line.

Also, type the **./logviewer.sh ./logs/civilian.log** ,
The basic class sample.SampleLogViewer cannot found. 
Is it a bug or is it not yet implemented? I want to know the location of the citizens in real time when running simulations.

Best regards,

**Comment by gnardin** [comment]
Dear @swhaKo,
There is no bug on these scripts or Java code. You are using both scripts incorrectly. The log file you should point to is the ```logs/rescue.log```. Therefore, the correct command-lines are ```./logextract.sh logs/rescue.log ./``` and ```./logviewer.sh logs/rescue.log```.

These tools allow you to analyze the simulation after it finished. To inspect the location of citizens or agents, you can use the tab "World view" in the "Kernel GUI" window that appear when you start the simulation. 

Please let me know if this works and if you need further assistance.

Best regards,

**Comment by swhaKo** [comment]
Thanks for the kind reply! Now I understand the point.

**Comment by AmazingTurtle** [comment]
Just wanted to leave that here..
https://chrisdown.name/2020/01/13/1195725856-and-friends-the-origins-of-mysterious-numbers.html

Seems like you're running a HTTP TRACE request against something, that accepts non-HTTP binary data.
