### ISSUE TITLE
How can I set the blockade rate at the start of the simulation? Is it in some .cfg file on config directory?

### ISSUE THREAD

**Issue by jpfsilvaa** [roborescue/rcrs-server#12]
Hi, I'm a graduation student, and I'm trying to use this version of the simulator. I'm new at this, and I'm having problems at the beggining of the simulation. It starts with a lot of blockades in the test map, and for my tests I would like it was a bit lower... Could someone help me?

**Comment by gnardin** [comment]
Dear @jpfsilvaa ,
You cannot set explicitly the amount of blockades, but you can change the Collapse settings to achieve what you are expecting. Below you find the list of parameters in the `collapse.cfg` file that allows you to deal with the number of blockades in the roads.
`collapse.create-road-blockages`        # create blockade or not
`collapse.floor-height`                          # It will effect the number of blockade do you want.
`collapse.wall-extent.min`                    # It will effect the number of blockade do you want.
`collapse.wall-extent.max`                   # It will effect the number of blockade do you want.

To change the clearing rate, please refer to the followning parameters in the `clear.cfg` file
`clear.repair.rate`              # Rate of clearing a road
`clear.repair.distance`       # Distance of the clearing operation
`clear.repair.rad`               # Width of clearing radius

Note that these configuration files are located by default in the `boot/config` directory, but you may specify other location when starting the simulator.

If you need further information, please us know.
Luis Gustavo Nardin

**Comment by jpfsilvaa** [comment]
I was trying to change this parameters but I wasn't specifying other location to the directory... Now it worked!

I'm going to continue my tests now, and if a need, I will ask you something else. Thank you!
João Paulo Francisco da Silva
