### ISSUE TITLE
Compiling error: ant cannot perform a complete-build

### ISSUE THREAD

**Issue by blmussati** [roborescue/rcrs-server#21]
I git clone this repository and checked my version of ant and java:
`Apache Ant(TM) version 1.10.5 compiled on July 10 2018`
`java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)`

so I meet the prerequisites

cd in my local `rcrs-server` directory
`ant clean-all` is successful
however
`ant complete-build` gives me the following error

> BUILD FAILED
.\rcrs-server\build-javadoc.xml:5: org.mozilla.javascript.EcmaError: ReferenceError: "load" is not defined.

why is this happening?

Thanks

**Comment by gnardin** [comment]
Hi @blmussati ,
Can you please send me the long list of messages that is console logged when you run the ``ant complete-build`` command?
Thanks,

**Comment by gnardin** [comment]
Hi @blmussati ,
I was already migrating the build tool used to compile the simulator from Ant to Gradle and I have just finished. I have just uploaded the new simulator version which uses Gradle to compile.
Please clone the ``rcrs-server`` again and run the simulator as described in the instructions in the README.md file.
Let me know if you experience any problem.
Best,

**Comment by gnardin** [comment]
Build tool migrated from Ant to Gradle.
