### ISSUE TITLE
Error launching `scenarioEditor` using Gradle

### ISSUE THREAD

**Issue by gnardin** [roborescue/rcrs-server#41]
> @gnardin
> 
> Yes, We knew that the same tools can be run via Gradle.
> By the way, these scripts are for the time that we do not use Gradle or having problem with Gradle.
> I tried to run the tools using Gradle and faced problem and could not run the tools, so started to write these shell scripts.
> By the way, I should mention that I could not run the tools using gradlew as follow
> $ ./gradlew scenarioEditor
> But I could run the tools as follow
> $ gradle scenarioEditor
> ![Screenshot from 2020-06-11 00-26-45](https://user-images.githubusercontent.com/30586155/84312531-547c1800-ab7a-11ea-8c2d-089008760840.png)
> ![Screenshot from 2020-06-11 00-26-45](https://user-images.githubusercontent.com/30586155/84312715-a9b82980-ab7a-11ea-93c8-05cf81a32bea.png)

This issue was opened by the request of @ffaraji

**Comment by gnardin** [comment]
@ffaraji 

To investigate what may cause the error, please provide the following list of information

- Gradle version (`$ gradle -version`)
- Execute the sequence of commands below and send the debug log generated by the last command
  ```
  $ ./gradlew clean
  $ ./gradlew completeBuild
  $ ./gradlew --debug scenarioEditor
  ```
- List of your `roborescue` directory showing the hidden directories and files (`$ ls -la`)
- Java Version (`$ java -version`)

Thank you,
@gnardin

**Comment by ffaraji** [comment]
@gnardin 

![Screenshot from 2020-06-12 02-12-47](https://user-images.githubusercontent.com/30586155/84442522-06871300-ac53-11ea-8cf8-f381205985b9.png)

![Screenshot from 2020-06-12 02-17-09](https://user-images.githubusercontent.com/30586155/84443273-819cf900-ac54-11ea-94b4-6e7cb0fe6db9.png)

![Screenshot from 2020-06-12 02-28-15](https://user-images.githubusercontent.com/30586155/84443278-8661ad00-ac54-11ea-81cf-aa93c80f22a7.png)

![Screenshot from 2020-06-12 02-30-11](https://user-images.githubusercontent.com/30586155/84443347-ab562000-ac54-11ea-8ccc-7772a7e0e23d.png)

![Screenshot from 2020-06-12 02-32-36](https://user-images.githubusercontent.com/30586155/84443523-0720a900-ac55-11ea-9692-77865bf5e5d8.png)

**Comment by gnardin** [comment]
@ffaraji 
Thank you for the detailed information.
The error is caused by an incompatibility of **Java 14** and **Gradle Wrapper 6.1.1**.

There are two possible workarounds:

1. Downgrade your Java to version 13
2. Change the file `gradle-wrapper.properties` under the directory `gradle/wrapper`. Replace
      `distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`
   by
      `distributionUrl=https\://services.gradle.org/distributions/gradle-6.4.1-all.zip`

Kind Regards,
@gnardin

**Comment by ffaraji** [comment]
@gnardin 
I used java14 and changed the gradle-warper.properties file and Replaced gradle-6.1.1 by gradle-6.4.1.
that works without error.
So we need to solve this problem that which version of java and gradle should be used.
By the way, as I said before, using system gradle to compile works fine but the problem occurs when we use gradlew.

**Comment by gnardin** [comment]
@ffaraji 
Gradle Wrapper was updated to support Java 14.
Can you please check in your environment the fix?

**Comment by gnardin** [comment]
Fixed. To launch the  **Scenario Editor** using Gradle, use the command `./gradlew scenarioEditor`.
