### ISSUE TITLE
ProtoBuf branch is not compatibile with the logs of traditional version 

### ISSUE THREAD

**Issue by modaresimr** [roborescue/rcrs-server#49]
I have seen that in the ProtoBuf branch URN_PREFIX has been eliminated. This will make an inconsistency in the old version logs. However, I agree that the prefix is useless and maybe waste a lot of memory. 
I think two ways exist to have compatibility with traditional version of the simulator:
- provide a wrapper to convert old logs to protobuf format and use it 
- use the old URN_PREFIX

**Comment by gnardin** [comment]
Are logs really used by teams to improve their implementation from one year to another to justify keeping the compatibility?
