### ISSUE TITLE
Merge enum and enum_v1 

### ISSUE THREAD

**Issue by modaresimr** [roborescue/rcrs-server#53]
In protobuf v5+ there is two enum
enum_v1 and enum
so they can be merged

**Comment by gnardin** [comment]
Dear @modaresimr 
I merged both enums and I made all the necessary changes in the `rcrs-server`, `rcrs-adf-core` and `rcrs-adf-sample` repositories.
The changes were included in the `protobuf-v6` branch (`rcrs-server`) and `protobuf-comm` (`rcrs-adf-core` and `rcrs-adf-sample`).
Please test the changes before we can close this issue.

**Comment by gnardin** [comment]
Resolved.
