### ISSUE TITLE
organisation of folders 

### ISSUE THREAD

**Issue by modaresimr** [roborescue/rcrs-server#54]

**Comment by gnardin** [comment]
I reorganized the folders and files in the project
* Moved the `oldsims` folder inside `modules` folder
* Renamed `boot` folder to `scripts`
* Moved the `config` and `logs` folder to the project root directory
* Moved the `supplement/log4j.properties` file to the `config` folder
* Moved the maps in the `glm` folder to the `maps` folder

All necessary changes in the scripts were done.

**Comment by gnardin** [comment]
Resolved.
