### ISSUE TITLE
Cannot get refill rate

### ISSUE THREAD

**Issue by okanasik** [roborescue/rcrs-server#6]
Currently, we cannot get refill rate with a config.
Maybe, it is a bug.
I think it can be fixed rewriting like below.
modules/standard/src/rescuecore2/standard/kernel/StandardAgentRegistrar.java:L48 VISIBLE_CONFIG_OPTIONS.add("fire\.tank\.refill-rate");
->
VISIBLE_CONFIG_OPTIONS.add("fire\.tank\.refill_rate");

https://sourceforge.net/p/roborescue/support-requests/3/

**Comment by kandeh** [comment]
It's also required to apply the same change in adf/agent/info/ScenarioInfo.java:L178.

**Comment by okanasik** [comment]
Dear @kandeh , you are right. I have created pull requests for both adf-core and rcrs-server. Best.

**Comment by gnardin** [comment]
Dear @okanasik ,
I have accepted the pull requests you submitted last week. Can I close this Issue?
Thank you,
Luis
