### ISSUE TITLE
Request for Modification Regarding Map Score Calculation Method

### ISSUE THREAD

**Issue by ItsukiMatsunaga** [roborescue/rcrs-server#65]
Hello, I'm a student at Nobuhiro's lab.
I'm involved in map creation. I have a question related to maps.
It is about the method of calculating scores for maps.
In the score.cfg file of each map, the score calculation method is set to
```
score.function : rescuecore2.standard.score.LegacyScoreFunction
```
However, I think this method also affects the score of fires that are not currently occurring.
Therefore, by using the following program, it is possible to calculate the score based only on the health of the citizens.
```
score.function : rescuecore2.standard.score.RSL21ScoreFunction
```
Could you please confirm and make the necessary modifications ?

**Comment by gnardin** [comment]
@ItsukiMatsunaga 
The score function of all maps in the `rcrs-server` was changed to `rescuecore2.standard.score.RSL21ScoreFunction`.

Please reopen the issue if there is any problem.
