### ISSUE TITLE
Is Gradle Required in Pre-installation for rcrs-server?

### ISSUE THREAD

**Issue by NONONOexe** [roborescue/rcrs-server#66]
Gradle is mentioned in the pre-installation section of the README. However, given that rcrs-server employs Gradlew (Gradle Wrapper), it may not be required. Is my understanding correct?

**Comment by gnardin** [comment]
Dear @NONONOexe 
You are correct. I have learned just recently that if we use Gradlew, we do not need Gradle installed. I will update the documentation.

**Comment by NONONOexe** [comment]
Dear @gnardin 
Thank you for your response.
