### ISSUE TITLE
Run server without any UI elements

### ISSUE THREAD

**Issue by Sebastian-GHub** [roborescue/rcrs-server#69]
Expected Behaviour:
using --nogui parameters should have everything running without any graphical interfaces.

Behaviour:
Even if using --nogui on simulators, kernel and viewers the SampleViewer will start on postConnect.

**Comment by gnardin** [comment]
@Sebastian-GHub 
Can you please share the commands you are using to run the simulator and the agents?

**Comment by gnardin** [comment]
@Sebastian-GHub 
I could not reproduce your problem. I run the following command from the `scripts` folder

`./start.sh --nogui -m ../maps/test/map/ -c ../maps/test/config/`

Then I launched the Sample Agent in another terminal.

No GUI was presented and the simulation ran correctly.

**Comment by Sebastian-GHub** [comment]
Yep... this one is on me. 
We created our own run config which directly took the --nogui parameter for startKernel and startSims, but still included the startViewer command. Should have double checked that. Sorry for causing confusion. I'll close this issue as this was obviously just our fault.
