### ISSUE TITLE
GUI exits automatically after all timesteps complete

### ISSUE THREAD

**Issue by XZJIsme** [roborescue/rcrs-server#73]
After completing all timesteps, the GUI automatically closes. I've been unable to find a way to prevent this behavior. Ideally, the GUI should remain open for further interaction or review once the process is complete. Any suggestions or guidance on how to keep the GUI active after all timesteps are finished would be greatly appreciated.

**Comment by gnardin** [comment]
Dear @XZJIsme 
This is the normal behavior of the simulator. There is no way to prevent this behavior.
If you want to analyze the simulation, you can use the LogViewer, a tool designed to inspect the simulation after it has finished. It allows you navigate manually through the simulation steps and check property value of different entities in the map.

Refer to the Section 4.4 in the manual [RoboCup Rescue Simulator Manual](https://roborescue.github.io/rcrs-server/rcrs-server/index.html) to know how to run the LogViewer. Unfortunately we do not have a manual explaining how to use the tool itself.

Please let us know if you have any further questions.

**Comment by XZJIsme** [comment]
thank you, now I see
